mdaus/coda-oss

build/build.py, modules/c++/sys/wscript
Introduces checks for c++11 support to coda.
=> Cpp11support

build/build.py
Adds C++11 support checking for g++ to waf.
=> Git some cpp11

modules/c++/math.linear/include/math/linear/Matrix2D.h, modules/c++/math.linear/include/math/linear/MatrixMxN.h, modules/c++/math.linear/include/math/linear/Vector.h, modules/c++/math.linear/include/math/linear/VectorN.h, modules/c++/math.poly/include/math/poly/OneD.h, modules/c++/math.poly/include/math/poly/OneD.hpp, modules/c++/math.poly/include/math/poly/TwoD.h
This should now be merge-ready with all the same changes I made in the branch math.linear_additions
=> Added math.poly and math.linear functionality to support mcad_analysis (#2)

modules/c++/math.linear/include/math/linear/Vector.h, modules/c++/math.linear/include/math/linear/VectorN.h
I had to fix two errors I made when switching my math.linear and math.poly changes to a new branch that was ready to merge into master.
=> Math.linear additions up

build/build.py
merge in --shared support for python libs as well as cleaned up swig_linkage
=> Python shared linkage

build/build.py
removed unwanted white space in soname
=> Fixed bug with soname, typo

modules/python/types/source/generated/coda_types.py, modules/python/types/source/generated/coda_types_wrap.cxx, modules/python/types/source/types.i
I am planning on using this in the CPHD reader.
=> Added RowCol<size_t> to be exported to python.

.gitignore
Ignore untarred driver folders
Ignore some extra files
=> Improve the .gitignore

build/build.py, modules/python/io/source/generated/coda_io.py, modules/python/io/source/generated/coda_io_wrap.cxx, modules/python/io/source/io.i, modules/python/io/wscript, modules/python/logging/source/generated/coda_logging.py, modules/python/logging/source/generated/coda_logging_wrap.cxx, modules/python/logging/source/logging.i, modules/python/logging/tests/test_logging.py, modules/python/logging/wscript, modules/python/types/source/generated/coda_types.py, modules/python/types/source/generated/coda_types_wrap.cxx, modules/python/types/source/types.i, modules/python/types/wscript
io, types, logging; sys and except had kept the prefix
=> Changed python naming back to prefix method

build/build.py
See comments for details, but long story short, Kyle had some logic in here which I think was trying to skip bad configurations and/or supported finding VS when using a regular command prompt... it was doing this by confirming all the paths in LIB were valid.  With VS2015 Express, not all paths in LIB are valid (because they're appended to some environment variables that aren't set), but the configuration itself is fine.  Removing this logic, VS2015 Express seems to work in both its own command prompt and the generic command prompt.  I have a theory that this is also what was causing the problems where some VS Pro installations couldn't use the x64 target, so I reverted out that hack too.
It's probably a decent bet that this will break really old versions of VS Express (2008 or 2010) …
=> Fixing build.py for VS 2015

modules/c++/mem/include/mem/BufferView.h
I don't know if throwing a string is the best, so let me know what to change it to if I should change it!
@mbojrab @jmrandol
=> Add BufferView::section() method

modules/c++/mem/include/mem/ScopedCloneablePtr.h, modules/c++/mem/include/mem/ScopedCopyablePtr.h
=> Adding constructor and reset() overloadings that take in an auto_ptr

modules/c++/net/include/net/Socket.h, modules/c++/net/source/Socket.cpp, modules/c++/net/tests/TCPClientSpeedTest.cpp, modules/c++/net/tests/TCPClientTest.cpp, modules/c++/net/tests/TCPServerSpeedTest.cpp, modules/c++/net/tests/TCPServerTest.cpp
Adding TCPClient/ServerSpeedTest applications that measure the speed of sending messages back and forth over a port via TCP
=> Add net speed tests

modules/c++/sys/source/ExecUnix.cpp
This is a pretty straigh-foward update. Not sure why I chose the other route as this was what popen is doing under the hood. Easy-Peasy.
=> Fixing the broken subprocess. This was unable to call shell commands like cd, as it was before

build/build.py
=> Adding C++11 support for Intel compiler

modules/c++/include/TestCase.h, modules/c++/sys/include/sys/AbstractOS.h, modules/c++/sys/include/sys/OSUnix.h, modules/c++/sys/include/sys/OSWin32.h, modules/c++/sys/source/AbstractOS.cpp, modules/c++/sys/source/OSUnix.cpp, modules/c++/sys/source/OSWin32.cpp, modules/c++/sys/unittests/test_os.cpp
Looks like I broke stuff on windows before with getEnv, so unfortunately this will be necessary to merge back in...
Also this should cover #82
=> Env unset and tests

modules/c++/plugin/include/plugin/ErrorHandler.h, modules/c++/sys/source/SemaphoreWin32.cpp
Just cleaning up a few things from my latest commits.
=> conform to coding convention

modules/python/mem/source/mem.i
Adding macros similar to the scoped copyable/cloneable types for SharedPtr
@chvink
=> Adding SharedPtr Python macros

build/build.py, build/dumpenv.py, build/dumplibimpl.py, build/pythontool.py, build/swig.py, modules/c++/sys/wscript, modules/drivers/fftw/wscript
I made an assumption that dir names would not require Unicode support.
=> Update build scripts to be dual-compatible with Python 2 and 3

modules/c++/sys/include/sys/FileFinder.h
Need to include string and utility
=> sys::FileFinder needs additional headers

build/build.py
Normally you want to just add an entire source directory but this allows you to list individual file(s) if that's useful (will be for NITRO)
=> Adding ability to list individual source files to bld.module()

modules/c++/sio.lite/wscript
=> Fixed maintainer

modules/c++/sys/include/sys/Backtrace.h, modules/c++/sys/source/Backtrace.cpp, modules/c++/sys/tests/TestBacktrace.cpp, modules/c++/sys/wscript
This function can help with debugging in some situations. With some extra work I can include a solaris and windows implementation, too.
=> Glibc backtrace

modules/c++/sys/source/Backtrace.cpp
This fixes the issue Jenkins found.
=> Fixed string literal

modules/python/mt/source/generated/mt_wrap.cxx, modules/python/types/source/generated/coda_types.py
Missed a few Swig-generated files in previous checkins
=> Missed some Swig-generated files

modules/python/math.poly/wscript
Just missed this in the wscript
@tolsonMDA
=> types-python should come in for math.poly too

build/dumpconfig.py, build/msvs.py, build/scripts/jenkins.py, build/scripts/makeInstallPath.py
With this update, the requested tests will all pass with Python 3. Also replaces tabs with spaces.
=> Update lingering issues that only worked in Python2

build/build.py, build/makewheel.py, build/package.py
Distro branch in SIX is also ready.
=> Add package and makewheel commands for distribution 

modules/c++/math.linear/wscript, modules/c++/math.poly/wscript
Need to handle if modules/drivers/boost doesn't exist (because we've trimmed down the drivers directory in another repo)
@mbojrab
=> Need to make HAVE_BOOST check smarter

modules/c++/re/source/RegexPCRE.cpp
Variable name out of sync
@clydestanfield
=> Fix PCRE build

modules/c++/logging/include/logging/LoggerFactory.h, modules/c++/logging/source/DefaultLogger.cpp, modules/c++/re/include/re/RegexPredicate.h, modules/c++/re/tests/benchmark_regex.cpp, modules/c++/sys/source/AbstractOS.cpp, modules/c++/sys/source/Backtrace.cpp, modules/c++/sys/tests/TestBacktrace.cpp, modules/c++/sys/unittests/test_os.cpp, modules/c++/xml.lite/include/xml/lite/Serializable.h, modules/c++/xml.lite/source/Serializable.cpp, modules/c++/xml.lite/tests/ValidationTest.cpp, modules/c++/zip/include/import/zip.h, modules/c++/zip/include/zip/GZipInputStream.h, modules/c++/zip/include/zip/GZipOutputStream.h, modules/c++/zip/include/zip/Types.h, modules/c++/zip/include/zip/ZipEntry.h, modules/c++/zip/include/zip/ZipFile.h, modules/c++/zip/source/GZipInputStream.cpp, modules/c++/zip/source/GZipOutputStream.cpp, modules/c++/zip/source/ZipEntry.cpp, modules/c++/zip/source/ZipFile.cpp, modules/c++/zip/tests/test_compress.cpp, modules/c++/zip/tests/test_decompress.cpp, modules/c++/zip/tests/test_pkunzip.cpp
=> Added banners

build/build.py, build/makewheel.py
For Issue #173 . 
Regarding the changes to build.py: I find myself dreading figuring out how it works whenever it needs to be modified, so I'm trying to clean it up a little bit whenever I'm working in the area.
=> Allow to specify targets for makewheel

modules/c++/mt/include/mt/ThreadPlanner.h, modules/c++/mt/source/ThreadPlanner.cpp, modules/c++/mt/unittests/ThreadPlannerTest.cpp
Also adding Doxygen comments.
Moving some stuff from the header that doesn't need to be inlined into the cpp
=> Adding method to determine how many threads will be used by ThreadPlanner

modules/c++/math/include/math/Utilities.h, modules/c++/math/source/Utilities.cpp, modules/c++/math/unittests/test_nChooseK.cpp, modules/c++/math/unittests/test_n_choose_k.cpp
This came up while I was working on the converter, and I thought it would be good here.
=> Add nChooseK function

modules/c++/math/include/math/Utilities.h, modules/c++/math/source/Utilities.cpp
This fixes a build error in internal CODA.
=> Fix imports

build/build.py
Fixes https://github.com/ngageoint/six-library/issues/43
=> Fix bug in creating __init__.py

modules/c++/mem/include/mem/BufferView.h
You'll want to set aside some time to review this...
=> split() method can be const

modules/c++/sys/include/sys/Conf.h
=> Removed a macro from sys/Conf.h that was conflicting with Apache Mesos

modules/c++/math/include/math/Constants.h
Trivial, but managed to cause its share of frustration.
=> Move curly brace to obvious location

modules/c++/math.linear/include/math/linear/Matrix2D.h, modules/c++/math.linear/unittests/test_inverse.cpp, modules/c++/math.linear/unittests/test_pseudo_inverse.cpp
`math::poly::fit()` and `math::linear::inverseLU()` aren't giving as good results as desired, so adding some tools to make it easy to do it myself.
=> Add function for computing pseudo-inverse

modules/c++/mem/include/mem/SwapBuffer.h
Useful to have a const version sometimes
=> Adding const overloadings

modules/c++/mt/include/mt/WorkSharingBalancedRunnable1D.h, modules/c++/mt/unittests/work_sharing_balanced_runnable_1d_test.cpp
The compiler was getting stuck and eventually running out of memory... this is why. :o)
=> runWorkSharingBalanced1DWithCopies() was calling itself

modules/c++/str/include/str/Convert.h
Matching https://github.com/mdaus/nitro/pull/65
FYI @s-martin
=> Avoiding namespace clash

modules/c++/except/include/except/Context.h, modules/c++/except/include/except/Trace.h, modules/c++/except/source/Context.cpp, modules/c++/except/source/Trace.cpp, modules/c++/except/tests/Gen2Test.cpp, modules/c++/logging/include/logging/Logger.h, modules/c++/logging/unittests/test_exception_logger.cpp, modules/c++/math.linear/include/math/linear/Matrix2D.h, modules/c++/math.linear/include/math/linear/MatrixMxN.h, modules/c++/math.linear/include/math/linear/Vector.h, modules/c++/math.linear/include/math/linear/VectorN.h, modules/c++/math.poly/include/math/poly/Fixed1D.h, modules/c++/math.poly/include/math/poly/Fixed2D.h, modules/c++/sys/include/sys/LocalDateTime.h, modules/c++/sys/include/sys/Path.h, modules/c++/sys/include/sys/UTCDateTime.h, modules/c++/sys/source/LocalDateTime.cpp, modules/c++/sys/source/Path.cpp, modules/c++/sys/source/UTCDateTime.cpp, modules/c++/unique/tests/UUIDGen.cpp, modules/c++/xml.lite/include/xml/lite/UtilitiesXerces.h, modules/c++/xml.lite/include/xml/lite/ValidatorInterface.h, modules/c++/xml.lite/include/xml/lite/ValidatorXerces.h, modules/c++/xml.lite/source/UtilitiesXerces.cpp, modules/c++/xml.lite/source/ValidatorXerces.cpp, modules/c++/zip/include/zip/ZipEntry.h, modules/c++/zip/include/zip/ZipFile.h, modules/c++/zip/source/ZipEntry.cpp, modules/c++/zip/source/ZipFile.cpp
https://stackoverflow.com/questions/2159713/overloading-output-operator-for-a-class-template-in-a-namespace
Fixes Mac build (#243)
=> Moving ostream operators inside namespace so ADL works

modules/c++/mem/include/mem/SharedPtrCpp11.h
I was able to reproduce the error that @dstarinshak was seeing. This seems to fix it.
=> Fixed Intel shared ptr

modules/python/sys/source/generated/coda_sys.py, modules/python/sys/source/generated/coda_sys_wrap.cxx, modules/python/sys/source/sys.i
Just exposes the sys/UTCDateTime.h object to python
=> Exposing the UTCDateTime class to python

modules/drivers/j2k/openjpeg/wscript
=> Fix linker errors when building from tarball

modules/drivers/j2k/openjpeg/wscript
=> Missed some indentation

modules/c++/math/include/math/Round.h
=> Need stddef.h for size_t

modules/c++/io/unittests/test_streams.cpp
=> Add missing include in unit test

modules/c++/xml.lite/source/XMLReaderXerces.cpp
https://github.com/mdaus/coda-oss/issues/280
=> Set feature flags to prevent hanging on DTDs

modules/c++/types/include/types/Range.h
This lets us use Range with an STL map
=> Adding Range operator<

modules/drivers/j2k/openjpeg/wscript
Fixed the call to targets_to_add()
=> OpenJPEG headers weren't getting installed

modules/python/sio.lite/source/generated/sio_lite_wrap.cxx
Apparently `waf clean` is required to get *everything*...
=> Update python bindings

modules/c++/mem/include/mem/ScopedCopyablePtr.h
GCC 4.4.7 gave a compile error here.
=> Only add explicit bool if we have C++11

modules/c++/sys/include/sys/ResourceCheck.h, modules/c++/sys/source/ResourceCheck.cpp
Somehow this got missed a couple times. It's needed for a few modules elsewhere and had been sitting uncommitted in my working directory here.
=> Added resource check functions to check process/system memory

build/build.py
=> Make build.py install Python unittests as well

modules/c++/sys/include/sys/ScopedCPUAffinityUnix.h
Should be the last one... Already been tested in Jenkins
=> Remove sys_config.h include

modules/c++/sys/include/sys/Err.h
Fixes https://github.com/mdaus/nitro/issues/180
=> Remove warning about uninitialized base class

modules/c++/io/include/io/FileInputStreamOS.h, modules/c++/io/include/io/NullStreams.h, modules/c++/io/include/io/StringStream.h, modules/c++/io/source/StreamSplitter.cpp, modules/c++/logging/source/Handler.cpp, modules/c++/mem/tests/ScratchVisualization.cpp
Fix a few compiler warnings when building with Visual Studio at /W4
=> fix compiler warnings

modules/c++/except/include/except/Context.h, modules/c++/except/include/except/Error.h, modules/c++/except/include/except/Exception.h, modules/c++/io/include/io/NullStreams.h, modules/c++/sys/include/sys/Conf.h, modules/c++/sys/include/sys/Err.h
remove code-analysis diagnostics
=> remove code-analysis diagnostics

modules/c++/include/TestCase.h, modules/drivers/xml/xerces/CMakeLists.txt
allow unittests to run in Visual Studio
=> allow unittests to run in Visual Studio

.gitignore, modules/drivers/j2k/openjpeg/CMakeLists.txt, modules/drivers/j2k/openjpeg/README, modules/drivers/j2k/openjpeg/wscript
=> update to openjpeg-2.3.1

modules/c++/sys/include/import/sys.h, modules/c++/sys/include/sys/Filesystem.h, modules/c++/sys/source/Filesystem.cpp
Don't get <filesystem> until C++17
=> sys/Filesystem as a work-around for no <filesystem>

modules/c++/io/include/io/NullStreams.h, modules/c++/sys/include/sys/Conf.h, modules/c++/sys/include/sys/ReadWriteMutex.h, modules/c++/sys/source/OSWin32.cpp
update "main" from develop/main
=> update "main" from develop/main

modules/c++/sys/include/sys/Bit.h, modules/c++/sys/include/sys/Conf.h, modules/c++/sys/include/sys/Filesystem.h, modules/c++/sys/unittests/test_byte_swap.cpp, modules/c++/sys/unittests/test_os.cpp
Not quite 100% kosher, but makes client code much simpler.
=> enable std::filesystem and std::endian

modules/c++/sys/include/import/sys.h, modules/c++/sys/include/sys/Filesystem.h, modules/c++/sys/source/Filesystem.cpp, modules/c++/sys/unittests/test_os.cpp
implement some `<filesystem>`-like routines until we can use C++17
=> implement some <filesystem>-like routines until we can use C++17

modules/c++/sys/include/import/sys.h, modules/c++/sys/include/sys/Bit.h, modules/c++/sys/unittests/test_byte_swap.cpp
implement sys::Endian from C++20
=> implement sys::Endian from C++20

modules/c++/except/include/except/Context.h, modules/c++/except/include/except/Error.h, modules/c++/except/include/except/Exception.h, modules/c++/include/TestCase.h, modules/c++/io/include/io/FileInputStreamOS.h, modules/c++/io/include/io/NullStreams.h, modules/c++/io/include/io/Seekable.h, modules/c++/io/include/io/StringStream.h, modules/c++/str/include/str/Convert.h, modules/c++/sys/include/sys/Err.h, modules/c++/sys/include/sys/FileFinder.h, modules/c++/sys/include/sys/ReadWriteMutex.h, modules/c++/sys/source/OSWin32.cpp, modules/c++/xml.lite/CMakeLists.txt, modules/c++/xml.lite/wscript
Fix several compiler warnings/code-analysis diagnostics.
=> fix several compiler warnings/code-analysis diagnostics

modules/c++/mt/source/ThreadGroup.cpp
=> latest from develop/main

modules/c++/math.linear/include/math/linear/Line2D.h, modules/c++/math.linear/source/Line2D.cpp
Changes to **math.linear** from coda.
=> changes to math.linear from coda

modules/c++/xml.lite/include/xml/lite/Document.h, modules/c++/xml.lite/unittests/test_soapelements.cpp
* Changed createElement to virtual to allow parsing of SOAP body
* WIP Initial Unit test
* Unit test dynamic cast
* Changed type to create error
* Changed cast type
=> Change xml lite function to virtual (#645)

modules/c++/CMakeLists.txt, modules/c++/coda_oss/include/coda_oss/optional_.h, modules/c++/config/include/config/disable_compiler_warnings.h, modules/c++/except/include/except/Context.h, modules/c++/except/include/except/Error.h, modules/c++/except/include/except/Exception.h, modules/c++/except/include/except/Throwable.h, modules/c++/except/source/Backtrace.cpp, modules/c++/hdf5.lite/include/hdf5/lite/SpanRC.h, modules/c++/hdf5.lite/unittests/test_hdf5write.cpp, modules/c++/io/source/InputStream.cpp, modules/c++/logging/include/logging/Enums.h, modules/c++/logging/include/logging/LogRecord.h, modules/c++/logging/source/Setup.cpp, modules/c++/logging/unittests/test_exception_logger.cpp, modules/c++/math.linear/unittests/test_lin.cpp, modules/c++/mt/unittests/Runnable1DTest.cpp, modules/c++/net/include/net/URL.h, modules/c++/net/source/URL.cpp, modules/c++/str/unittests/test_base_convert.cpp, modules/c++/sys/include/sys/Conf.h, modules/c++/sys/include/sys/DateTime.h, modules/c++/sys/include/sys/Dbg.h, modules/c++/sys/include/sys/OS.h, modules/c++/sys/unittests/test_NaN_testing.cpp, modules/c++/sys/unittests/test_os.cpp, modules/c++/sys/unittests/test_path.cpp, modules/c++/xml.lite/unittests/test_soapelements.cpp, modules/c++/xml.lite/unittests/test_xmlparser.cpp
Build cleanly with all G++ warnings enabled! :-)
=> build cleanly with all G++ warnings enabled

.github/workflows/build_unittest.yml
=> change actions to @v3

.github/workflows/build_unittest.yml
`--output-on-failure` for CTest
=> --output-on-failure for CTest

modules/c++/coda_oss/include/coda_oss/cstddef.h, modules/c++/std/include/std/cstddef
https://en.cppreference.com/w/cpp/types/byte "`std::byte` is a distinct type ..."
=> std::byte should be a unique type

modules/c++/sys/include/sys/AbstractOS.h, modules/c++/sys/source/AbstractOS.cpp, modules/c++/xml.lite/include/xml/lite/Attributes.h, modules/c++/xml.lite/include/xml/lite/ValidatorInterface.h, modules/c++/xml.lite/include/xml/lite/ValidatorXerces.h, modules/c++/xml.lite/source/ValidatorXerces.cpp
*xml.lite* tweaks to support using two different ISMs in SIDD 3.0.
=> xml.lite tweaks to support SIDD 3.0 ISM

ReleaseNotes.md, modules/c++/config/include/config/Version.h
* *zlib* updated to [1.2.13](https://github.com/madler/zlib/releases/tag/v1.2.13).
* new `mem::ComplexView` class to make it easier to process complex data stored in parallel. 
* adjust compiler flags for clean *CMake* builds.
* wrap common "file open" routines (e.g., `fopen()`) to support `sys::expandEnvironmentVariables()`.
* add header-only [HighFive](https://github.com/BlueBrain/HighFive) HDF5-wrapper library.
* Added a handful of [HighFive](https://github.com/BlueBrain/HighFive) utility routines.
* `mt::transform_async()` removed, it doesn't match C++17 techniques.'
* Revamp `sys::byteSwap()` for improved type-safety and
[better performance](https://devblogs.microsoft.com/cppblog/a-tour-of-4-msvc-backend-improvements/).
* Added case-insensitive string comparison utilties: `str::eq()` …
=> coda-oss release 2023-06-06

ReleaseNotes.md, modules/drivers/xml/xerces/CMakeLists.txt, modules/drivers/xml/xerces/wscript
[xerces-c](https://xerces.apache.org/xerces-c/) [3.2.4](https://issues.apache.org/jira/secure/ReleaseNote.jspa?version=12350542&styleName=Text&projectId=10510)
=> xerces-c 3.2.4

modules/c++/coda-oss.vcxproj, modules/c++/io/include/io/Serializable.h, modules/c++/logging/include/logging/Setup.h, modules/c++/plugin/include/plugin/ErrorHandler.h, modules/c++/sys/include/sys/DLL.h, modules/c++/sys/include/sys/FileFinder.h, modules/c++/sys/include/sys/sys_filesystem.h, modules/c++/tiff/include/tiff/FileReader.h, modules/c++/tiff/include/tiff/FileWriter.h, modules/c++/tiff/include/tiff/Header.h, modules/c++/tiff/include/tiff/IFD.h, modules/c++/tiff/include/tiff/IFDEntry.h, modules/c++/tiff/include/tiff/ImageReader.h, modules/c++/tiff/include/tiff/ImageWriter.h, modules/c++/tiff/include/tiff/KnownTags.h, modules/c++/tiff/include/tiff/TiffFileReader.h, modules/c++/tiff/include/tiff/TiffFileWriter.h, modules/c++/tiff/include/tiff/TypeFactory.h, modules/c++/tiff/source/KnownTags.cpp, modules/c++/xml.lite/include/xml/lite/Element.h
Export additional symbols to build SIX components as DLLs.
=> export more symbols

.github/workflows/build_unittest.yml
=> attempt allow build of pull requests

.github/workflows/build_unittest.yml
- dial back to ubuntu-22.04 to fix build
=> Restore ci to working order

cmake/CodaBuild.cmake, modules/c++/io/CMakeLists.txt, modules/c++/io/include/io/FileInputStreamOS.h, modules/c++/io/source/FileInputStreamOS.cpp, modules/c++/io/unittests/test_parallel_reads.cpp, modules/c++/io/wscript, modules/c++/sys/include/sys/File.h, modules/c++/sys/source/FileUnix.cpp, modules/c++/sys/source/FileWin32.cpp
Parallel file reads through io::FileInputStreamOS for high-performance reading of large contiguous file blocks
=> Parallel file reads through io::FileInputStreamOS

.github/workflows/build_unittest.yml, CMakeLists.txt, modules/c++/coda_oss.json/include/coda_oss/json/Math.h, modules/c++/coda_oss.json/unittests/test_json_math.cpp, modules/c++/math.poly/include/math/poly/Fixed1D.h, modules/c++/math.poly/include/math/poly/Fixed2D.h
- Add fixed size polynomial json
- Fix workflow cmake build configuration
- CXX standard configurable from higher level project
=> Some Updates
