build/scripts/jenkins.py
build/scripts/makeInstallPath.py

The Git Commit IDs are shortened to the last eight characters of the ID

Updating jenkins files to reflect Git ID rather than SVN ID in file path

---

modules/c++/sys/source/FileWin32.cpp

Same issue as reader, but with the writer. The bytesToWrite needs to be calculated using a size_t instead of a DWORD.

bytesToWrite now is calculated against a size_t.

---

build/build.py
modules/c++/sys/wscript

This allows c++11 usage to be determined at configure-time. There is also support for allowing wscripts to force c++11 usage via the 'force_cpp11support' parameter.

Cpp11 switch

---

build/javatool.py

I'm not sure there is a case when the user will want to specify a jar, and add it to the install_tgts. There was a bug with the former logic on Windows. Nitro still works as expected, and this fixes my use case.

update to the logic in classpath section. 

---

modules/c++/types/include/types/RowCol.h

Visual Studio 2010 was unable to resolve the sqrt for size_t or sys::SSize_T, so because this isn't heavily used and types doesn't depend on sys, we perform a cast to double to make the template we intend to use explicit. This is a little unfortunate.

Types row col sqrt fix for windows

---

modules/python/mem/source/mem.i

This is needed to prevent name conflicts across modules.

Added ability to rename Swig'd smart pointer in macro

---

modules/python/sys/source/sys.i

We need this for our bindings elsewhere. There are several sets of typemaps here because I suspect the one set would have trouble on windows. I'm not sure why but sys::Off_T does not actually match usages of sys::Off_T. 
Adding the typemaps didn't seem to change the cxx and py wrappers either.

Adding a typemap for Off_T

---

build/swig.py

Quick fix to exposing additional build problems in Windows. This does not get Windows able to generate the py files, but at least formats the compile properly to see the other errors. More work is needed here.

swig only recognizes -D for defines, so \D for windows conflicted.

---

build/build.py

There was a bug here where if you ran `./waf build` prior to installing a python module the `__init__.py` would not get installed correctly. Since the python interface doesn't really work without installation anyway I added a check to only run the `__init__.py` installation during install and that seems to have fixed it.

Added check for __init__.py installation

---

build/build.py

Otherwise, with gcc and C++11 support we get warnings about auto_ptr being deprecated, which is true, but we need to continue to use it until we can require a C++11 compiler.

Turning off warning about deprecated declarations

---

build/javatool.py

This adds the same "automatic copy" for conf/ directories in the java modules. I tested this works in Nitro's java layer. I'm using this on FSG to copy my user manuals to the installation folder for each PIMA plugin.

Conf/ functionality for Java modules

---

modules/c++/sys/source/OSUnix.cpp
modules/c++/sys/tests/OSTest.cpp

This was a quick fix to get coda-oss working on OS X. Most of the OSUnix implementation works fine on OS X it seems, but it would be worth looking this over again if we need to add more to sys or expand support to other *nix systems.

Osx config

---

build/build.py

This branch adds OSX support for building python bindings, and also fixes an issue present for `ld` versions >2.17.

Python ld update

---

modules/c++/logging/include/logging/Logger.h

Logically a Logger should probably be noncopyable.  Old implementation resulted in a double delete when copying.

Logger should be noncopyable

---

modules/c++/sio.lite/include/sio/lite/FileHeader.h
modules/c++/sio.lite/source/FileHeader.cpp
modules/python/sio.lite/source/generated/sio_lite.py
modules/python/sio.lite/source/generated/sio_lite_wrap.cxx
modules/python/sio.lite/source/sio_lite.i

Large NumPy arrays going to/from C++ did not work properly on 64-bit Windows because Swig was trying to use a `long` to represent a `size_t` (which is 8 bytes on Unix so is ok but only 4 bytes on Windows)... you got a cryptic runtime error about it not being able to find the appropriate function because the conversion would fail in the C++ bindings.  To force Swig to generate C++ code with an 8 byte type, the only thing that seemed to make it do this was using `long long` (seems like it should have been smarter with `size_t` than it was).
@chvink @clydestanfield

Long long swig fix

---

modules/c++/net.ssl/include/net/ssl/SSLConnection.h
modules/c++/net.ssl/include/net/ssl/SSLConnectionClientFactory.h
modules/c++/net.ssl/source/SSLConnection.cpp
modules/c++/net.ssl/source/SSLConnectionClientFactory.cpp
modules/c++/net.ssl/tests/SSLTestClientNoURL.cpp
modules/c++/net.ssl/wscript

net.ssl now finds the openssl libraries and builds all its source by default.
There is an interface change between openssl 0.9.8(open) and openssl 1.0(back). I resolved this by building a fragment to determine which version we are using. If there is a better way to resolve this let me know.

Updates to net.ssl 

---

modules/c++/net/include/net/NetConnectionClientFactory.h

The Open SSL connection needs to be able to override this function.

Allow newConnection Overrides

---

modules/c++/net/source/Socket.cpp

Broke the Windows build when changing things over to `void*`... `sendto()` on Unix takes in the buffer as `const void*` but on Windows it's `const char*`, so need to add a cast

sendto() on Windows wants const char*

---

modules/c++/math.poly/include/math/poly/Fit.h
modules/python/math.poly/source/generated/math_poly.py
modules/python/math.poly/source/generated/math_poly_wrap.cxx

Vector3 poly fit overloading was providing one term less than was requested.  Renamed 'numCoeffs' to 'order' throughout for clarity.

Fixed bug in Vector3 poly fit overloading

---

build/build.py

Intel compiler doesn't have Wno-deprecated-declarations flag

---

modules/c++/net/tests/TCPServerSpeedTest.cpp

On a different Windows machine, the compiler was giving an error about an ambiguous overload of std::min. This fixes the issue.

Specify std::min overload

---

modules/c++/sys/include/sys/AbstractOS.h
modules/c++/sys/include/sys/OSUnix.h
modules/c++/sys/include/sys/OSWin32.h
modules/c++/sys/source/AbstractOS.cpp
modules/c++/sys/source/OSUnix.cpp
modules/c++/sys/source/OSWin32.cpp

Picked up some non-code changes  e.g. OSUnix.cpp:257-260 -> 281-284.  Not really sure why, but nothing should have changed in there.
Built on Win & Unix since there's define guards that change compilation on OS type.  Any testing recommendations welcome too.  Didn't see any tests pertaining to env var in the code base.  Could add a couple, but all I can reasonably think of is:  set -> isenvset -> get .   Let me know what you think here.
Also I added some more duplication of code between Win32 and Unix.  I chose to kept the abstract base class empty, but it might be better from a maintenance standpoint to put that in the base class, so feedback there would also be useful.

Added isSetEnv and getEnvIfSet

---

modules/c++/str/source/Manip.cpp

See http://en.cppreference.com/w/c/string/byte/tolower
In particular: character to be converted. If the value of ch is not representable as unsigned char and does not equal EOF, the behavior is undefined.
The undefined behavior on windows is to crash.
I added an helper function for std::transform that makes sure the characters are valid. An exception is thrown otherwise.

str::lower and str::upper can fail/crash if a string contains a signed char

---

modules/c++/sys/include/sys/SemaphoreWin32.h
modules/c++/sys/source/SemaphoreWin32.cpp

`sys::SemaphoreWin32` has a max count data type of `LONG` which is a valid Windows #define. However, some evil libraries define that or undefine it for themselves, so we should only reference it in the .cpp file not the .h file. Modify the class definition and .h file to use a `size_t` for max count, then cast to `LONG` in the .cpp file.

sys::SemaphoreWin32 max count data type 

---

modules/c++/plugin/include/plugin/ErrorHandler.h
modules/c++/plugin/source/ErrorHandler.cpp
modules/c++/plugin/wscript

When the plugin manager finds a DLL or SO that doesn't fit the "plugin" mold, it prints out a warning to stdout or stderr "Warning: plugin manager failed to load: Failed to load function: GetPluginIdentity: The specified procedure could not be found"
I added an optional logger to `DefaultErrorHandler` that will pass all messages to the logger rather than cout when specified. The plugin module now has a dependency on the logging module because of this.

Remove plugin manager warning

---

modules/c++/logging/include/logging/Logger.h
modules/c++/logging/include/logging/Setup.h
modules/c++/logging/source/Setup.cpp
modules/c++/plugin/include/plugin/ErrorHandler.h
modules/c++/plugin/source/ErrorHandler.cpp
modules/c++/xml.lite/tests/ValidationTest.cpp

As discussed with @msciaramitaro and @asylvest, removing `TaskErrorHandler` broke some behaviors others relied on. This fixes some of it.

Make the logger member of DefaultErrorHandler a SharedPtr & reduce some log levels.

---

modules/c++/math.linear/include/math/linear/MatrixMxN.h
modules/c++/math.linear/unittests/test_inf_equality.cpp

Previously, equals(infinity, infinity) returned false.

Inf equality

---

modules/c++/mem/include/mem/BufferView.h

Don't want implicit conversions from pointer types to `BufferView`s.  That is, we don't want...
```
void foo(mem::BufferView<float> values)
{
}
void someFunc()
{
float* ptr = new float[10];
foo(ptr);
}
```
to compile, but previously it would have since the second constructor argument to `BufferView` defaults to 0... it'll look like they passed in a `BufferView` with no bytes.  Just need to add `explicit` to the `BufferView` constructor.

BufferView constructor should be explicit

---

modules/c++/mem/include/mem/SharedPtr.h
modules/c++/mem/unittests/test_shared_ptr.cpp

This is for issue #103 
I added a overload for `mem::SharedPtr<T>::reset` that takes in an `std::auto_ptr<T>` and did a bit of refactoring so we could use the existing code for `reset()`. Also added a unit test.

Add a reset() overload for mem::SharedPtr which takes an auto_ptr

---

modules/c++/mem/include/mem/VectorOfPointers.h
modules/c++/mem/unittests/test_vector_pointers.cpp

As I'm going through some SDS code, I found a similar class in that codebase to our `mem::VectorOfPointers`, so I removed it and added the `erase()` function to CODA's so we can instead use the CODA version.

mem::VectorOfPointers<>::erase

---

modules/c++/str/source/Manip.cpp

Throwing when we come across a `char` that has undefined behavior when passed to `tolower()` or `toupper()` isn't very helpful to the user, and also breaks existing programs in the case the system's implementation chose to just no-op it too.

No-Op invalid characters that are passed to str::upper and str::lower

---

modules/c++/types/include/types/RowCol.h
modules/python/types/source/generated/coda_types.py
modules/python/types/source/generated/coda_types_wrap.cxx

`RowCol::normL1()` is really an area calculation, not a norm L1 calculation.  Renaming method to be consistent... if a norm L1 calculation is really needed down the road, we can add it, but we'll push this method out first so users see compiler errors and get a chance to fix things rather than getting incorrect behavior.
@jmrandol 
@apakanati 
@JonathanMeans 
@clydestanfield 
@mbojrab 
@msciaramitaro

Renaming RowCol's normL1() to area()

---

modules/c++/numpyutils/examples/scripts/numpyutilstest.py
modules/c++/numpyutils/examples/source/generated/numpyutilstest_wrap.cxx
modules/c++/numpyutils/examples/source/numpyutilstest.i
modules/c++/numpyutils/examples/wscript
modules/c++/numpyutils/include/numpyutils/numpyutils.h
modules/c++/numpyutils/source/numpyutils.cpp
modules/c++/numpyutils/wscript

Take a look at the #define stuff I added in the .h.  I'm not really sure this was a good idea, but as a brief explanation of what's going on.
- we're including numpy headers in the numpyutils header
- this means that all downstream compilation units get a warning because they don't have their own import_arrays call
- I tried some gymnastics with forward declaring numpy stuff, but ran into some trouble with C and typedef forwards and gave up on the basis of not being worth the time.  Not sure if this is possible but this might be an a good alternative (and would have the benefit of not appearing to provide numpy operators to downstream modules) when we don't safely
So I settled on this to #define NO_IMPORT which causes the header to suppress those warnings (and the definitions of …

Numpyutils update2

---

modules/c++/numpyutils/wscript
modules/drivers/numpy/wscript

I missed this when I moved this code into coda-oss. Jeff Pursell found the problem earlier today.
1. Added check to make sure python is enabled.
2. conf.check won't throw unless mandatory is true, getting a false positive if numpy/python were missing.
3. The msg() was unnecessary.

Made numpy driver more robust

---

modules/c++/math.linear/include/math/linear/Matrix2D.h
modules/c++/math.poly/include/math/poly/Fit.h
modules/c++/math.poly/unittests/test_llsq.cpp

Center input values for 2D polynomial fit.
The unit test has been updated with a more stressing test using more points and a higher order polynomial.  The previous version of math::poly::fit would fail this test with a mean residual error of 4.96674e+12.  The new version achieves a mean residual error of 1.39047e-14.

Center input values being used for 2D poly fit

---

modules/python/math.poly/source/generated/math_poly_wrap.cxx
modules/python/math.poly/source/math_poly.i

This corrects a syntax error that so far only gets caught on the SunC++ compiler.

Fix syntax error

---

modules/drivers/numpy/wscript

If we don't load `pythontool`, still need to be able to step through modules/drivers/numpy/wscript.  Need a `hasattr()` in there.
@chvink @apakanati

Need a hasattr() check in case Options.options.python isn't there

---

modules/python/sys/source/sys.i

The original code didn't bind to anything.

Changed Int64_T python typemap

---

modules/c++/numpyutils/include/numpyutils/numpyutils.h
modules/drivers/numpy/wscript

This solves the "Must use Python with unicode enabled" issue we've seen in a few places.

Versions of numpy prior to 1.10 require Python.h be included manually

---

modules/c++/math.poly/include/math/poly/OneD.hpp
modules/c++/math.poly/include/math/poly/TwoD.hpp
modules/c++/str/source/Manip.cpp

Fixing warnings on Windows in str and math.poly

Fixing Windows signed/unsigned and unsigned int vs. size_t type warnings

---

modules/c++/xml.lite/include/xml/lite/ValidatorInterface.h
modules/c++/xml.lite/source/UtilitiesXerces.cpp
modules/c++/xml.lite/wscript

Cleaning up a few warnings on Windows about unused variables

Xml lite warnings

---

modules/python/types/source/types.i
modules/python/types/tests/test_coda_types.py

By default, swig-wrapped objects do not play nicely with pickle (because the python layer doesn’t necessarily know how to serialize the c++ data), so this revision adds python extensions for the templated types defined in types.i.

Extended python coda_types to support pickling.

---

modules/c++/math.linear/include/math/linear/Matrix2D.h
modules/c++/math.linear/include/math/linear/MatrixMxN.h
modules/c++/math.linear/include/math/linear/Vector.h
modules/c++/math.linear/include/math/linear/VectorN.h
modules/c++/math.linear/unittests/test_Vector.cpp
modules/c++/math.linear/unittests/test_VectorN.cpp
modules/c++/math.linear/unittests/test_mx.cpp

Added negation operator to Matrix2D, MatrixMxN, Vector, and VectorN, as well as unit tests.  Now you can do:
`  Matrix2D B = -A;`

add negation operators to math.linear objects

---

modules/c++/math.poly/include/math/poly/Fit.h
modules/c++/math.poly/unittests/test_llsq.cpp

math::poly::fit() throws if not enough points to constrain fit to unique solution; added unit tests for this.  For 1D case throw if npoints < order+1.  For 2D case throw if npoints < (orderX+1) * (orderY+1).  Essentially you need at least as many points as coefficients in your polynomial, or there are infinite solutions and the returned polynomial could be any of them (probably not what you want).

Throw exception for invalid fit (not enough points)

---

build/swig.py

Two things here. I had to change the call to self.msg because option isn't a keyword argument. (docs: https://waf.io/apidocs/Context.html#waflib.Context.Context.msg)
And then it didn't actually do anything if it couldn't find the minimum version.

Fix checking for SWIG version

---

build/build.py
modules/c++/re/wscript

`PCRE2_STATIC` is not getting set in one additional spot which is causing linking issues on Windows

Fix PCRE 10.22 linking on Windows

---

modules/c++/re/source/RegexPCRE.cpp
modules/c++/re/unittests/test_regex.cpp

I think this is correct?
I had to use the actual call in the net module to reproduce the issue. Using (abc)(d?)(efg) with "abcdefg" and "abcefg" would work as is. I am not regex savvy enough to parse everything going on in that call (I tried to put it into some online checkers and several of them failed on it).
This does work with the stl version of regex but that one always returns the maximum number of matches with extra empty strings at the end which is why line 81 is a check for GREATER rather than EQ. It looked like the code was setup to handle a variable number of returns so I assume PCRE is correct here (at least for our purposes). Do we want to change the stl version so it looks for trailing empty strings and removes them?

Regex url fix

---

build/build.py

Updated the recurse directories so drivers would always be first. This ensures things like libssh and AWS will be configured before checking for them in the env dictionary.

Updated build.py recurse directories

---

build/swig.py
modules/c++/numpyutils/examples/source/generated/numpyutilstest_wrap.cxx
modules/python/except/source/generated/coda_except_wrap.cxx
modules/python/io/source/generated/coda_io_wrap.cxx
modules/python/logging/source/generated/coda_logging_wrap.cxx
modules/python/math.linear/source/generated/math_linear_wrap.cxx
modules/python/math.poly/source/generated/math_poly_wrap.cxx
modules/python/mem/source/generated/mem_wrap.cxx
modules/python/mt/source/generated/mt.py
modules/python/mt/source/generated/mt_wrap.cxx
modules/python/sio.lite/source/generated/sio_lite_wrap.cxx
modules/python/sys/source/generated/coda_sys_wrap.cxx
modules/python/types/source/generated/coda_types_wrap.cxx
modules/python/xml.lite/source/generated/xml_lite_wrap.cxx

This change is a global swig script change in order to change default SWIG behavior.  
In short, SWIG has an awesome default setting whereby depending on the number of elements in a vector, there is a covariant return type.
That is to say:
- a std::vector<T> of size 0 returns a tuple '()'
- a std::vector<T> of size 1 returns a T
- a std::vector<T> of size >1 returns a vector<T>
This introduces potentially really annoying handling at the python level.  I don't think that this is a good thing for us, and the benefit of whatever saving that might be is probably overwhelmed by the extra code maintenance.
After some digging, I came across this flag.  I think this is probably unintended behavior globally, so I've chosen to set a flag in swig.py unless -noextranative is explicitly passed:
If …

defaulting SWIG_PYTHON_EXTRA_NATIVE_CONTAINERS

---

modules/c++/mt/include/mt/LinuxCPUAffinityThreadInitializer.h
modules/c++/sys/source/ExecUnix.cpp

`execl()` wanting a cast was a compiler warning
Not finding `linux/unistd.h` was an error

Two minor gcc 6.2 / Alpine Linux fixes

---

build/build.py

I am very occasionally, (maybe 1 time in 7?) getting an error while installing: ` '/data1/u/jmeans/coda/install/lib/python2.7/site-packages/coda/__init__.py' does not exist`
Haven't figured out how to reliably reproduce it yet. Until it's fixed, I think it's better to have __init__.py not be installed in certain, rare, known circumstances, than to have the install randomly fail.

Revert __init__.py change

---

build/build.py

I've verified through prints that python_package(), when called from SIX, only gets called twice (coda and pysix). If I'm right about what the problem is, this will fix it. Don't know how to be more sure, short of re-installing several dozen times.

 Only create one __init__.py per project, to prevent race conditions  

---

build/build.py

I believe this will fix the Jenkins error we currently have.
It seems that install_tgt took in tsk as its first parameter instead of self. I updated the call to have it take in self instead. I am not sure what the original intent of the first parameter being tsk was, but I tested both "python waf install" and "python waf list" with "--install-source" and this seems to work.
@JonathanMeans

Install tgt fix

---

modules/drivers/curl/wscript

I ran into a case where one of our net libraries wouldn't compile because configuration couldn't implicitly link to libcurl, this will always explicitly link to it.

Some systems require explicitly adding curl to link line

---

modules/c++/sio.lite/include/sio/lite/ReadUtils.h

Doesn't look like this include guard was used elsewhere but it's still a mismatch.

Typo in include guard

---

modules/drivers/curl/wscript

Otherwise it ends up in the waf environment variables

Undefine HAVE_CURL_GLOBAL_INIT

---

modules/c++/include/TestCase.h
modules/c++/sys/unittests/test_NaN_testing.cpp

I ran into some surprises while testing.

 Make some test macros work against NaNs 

---

modules/c++/logging/include/logging/StreamHandler.h
modules/c++/logging/source/Handler.cpp
modules/c++/logging/source/StreamHandler.cpp

This updates the StreamHandler to no longer call a virtual method from inside its destructor.

Updated handlers to avoid calling virtual methods in the destructor

---

modules/c++/net.ssl/wscript

More systems than just solaris require this explicit linking, and it
doesn't seem to hurt systems where it's implicitly linked.

Always explicitly link to libcrypto if using net.ssl

---

modules/c++/sys/source/DateTime.cpp

Pointer should be dereferenced - the check is trying to find the end of the string.
FYI @clydestanfield @chvink

Fixing pointer check in strptime()

---

modules/c++/sys/include/sys/File.h
modules/c++/sys/source/FileUnix.cpp

These are deprecated in C++11.  They weren't compiling on Windows with gcc because FileWin32.cpp didn't have them in (I guess VS didn't care).
FYI @clydestanfield @chvink

Removing exception specifications from sys::File

---

build/build.py

Need to shift around a few things in `build.py` to get this to work where we assumed we were always using Visual Studio.
FYI @clydestanfield @chvink @JonathanMeans

Supporting gcc on Windows

---

modules/c++/logging/include/logging/XMLFormatter.h
modules/c++/logging/source/XMLFormatter.cpp
modules/c++/str/include/str/Manip.h
modules/c++/str/source/Manip.cpp
modules/c++/str/unittests/test_str.cpp

We have a need for this functionality elsewhere... originally I was going to put it in xml.lite but then I saw that logging::XMLFormatter was actually already doing what I wanted to do (but could have been using `str::replaceAll()` to simplify it.  `logging` doesn't depend on `xml.lite`, so rather than add a dependency I put the functionality in `str` (which you could argue has no business knowing about XML but neither did `logging`).  I think it's more useful to have it here than it is to have two versions of the same code.  Added unittests for it.

Want a standalone utility that knows how to escape XML characters

---

modules/c++/mt/source/ThreadPlanner.cpp

If there are no elements per thread, you will simply use 0 threads.  This is way better than dividing / modulo'ing by 0 and getting everyone upset.

Guarding against dividing / modulo'ing by 0

---

modules/python/sio.lite/source/generated/sio_lite.py
modules/python/sio.lite/source/sio_lite.i

Previously, it would throw an exception here for trying to concatenate string and int.

Fix exception message for unrecognizable data type

---

modules/c++/sys/source/FileWin32.cpp

Had an extra `const` in the cast that I had done blind

Fix Windows cast

---

modules/drivers/xml/xerces/wscript
modules/drivers/zlib/wscript

NRTAPI and NITFAPI are defined to be the appropriate __declspec statement.  Once this is merged, we will be able to do
```
python waf configure --prefix=install install
python waf configure --prefix=install --shared install
```and have DLLs for the C layer.

Fix bugs when building drivers with --shared flag

---

modules/c++/sys/source/ExecUnix.cpp

Previously, only stdout was saved when calling a command using a pipe. This also dup's the file descriptor to stderr.

Keep both stdout and stderr of a piped command

---

modules/c++/mem/include/mem/SharedPtr.h
modules/c++/mem/include/mem/SharedPtrCpp11.h
modules/c++/mem/include/mem/SharedPtrLegacy.h
modules/c++/mem/unittests/test_shared_ptr.cpp
modules/c++/mt/include/mt/BalancedRunnable1D.h
modules/c++/mt/include/mt/WorkSharingBalancedRunnable1D.h

C++11 mem::SharedPtr now inherits from std::shared_ptr.
The unittest has been updated to test C++11 support.

SharedPtr C++11 Update

---

build/build.py

This brings in most of the `build.py` changes from https://github.com/ngageoint/six-library/pull/191.  Need to generalize the Python bindings checks, but I think Mac should build with `--disable-python` after this.

Supporting Mac aside from Python bindings

---

build/build.py

Unfortunately, `2to3` does not catch this kind of thing.

Force string in check_output

---

modules/c++/xml.lite/source/XMLReaderXerces.cpp
modules/c++/xml.lite/wscript

This memory leak triggers when `MinidomParser.parse()` throws, which I forced by giving it non-xml data. I'm uncertain if it's the same one they were seeing.
I agree that the destructor logic looks correct...

Fix memory leak on error reading

---

modules/python/except/source/generated/coda_except.py
modules/python/io/source/generated/coda_io.py
modules/python/io/source/generated/coda_io_wrap.cxx
modules/python/io/source/io.i
modules/python/logging/source/generated/coda_logging.py
modules/python/math.linear/source/generated/math_linear.py
modules/python/math.poly/source/generated/math_poly.py
modules/python/mt/source/generated/mt.py
modules/python/sio.lite/source/generated/sio_lite.py
modules/python/sys/source/generated/coda_sys.py
modules/python/types/source/generated/coda_types.py
modules/python/xml.lite/source/generated/xml_lite.py

There's a lot of noise here. The only actual change is adding `#define SWIG_PYTHON_STRICT_BYTE_CHAR` in `io.i`

Allow io to read from bytes object in Python3

---

modules/c++/mem/include/mem/ScratchMemory.h
modules/c++/mem/include/mem/ScratchMemory.hpp
modules/c++/mem/source/ScratchMemory.cpp
modules/c++/mem/unittests/test_scratch_memory.cpp

A new method getBufferView helps to simplify usage of ScratchMemory in constructor initializer lists.

Add convenience methods to get buffer view of scratch segment.

---

modules/c++/sio.lite/include/sio/lite/ElementType.h

Allows reading SIOs of type complex<double>, here an alias for reading complex<float>.

Read SIOs of type complex<double> (reuses the complex<float> case)

---

modules/c++/math/include/math/Constants.h
modules/c++/math/source/Constants.cpp

We were multiplying by feet to meters rather than meters to feet

Fixed bug in nautical miles to feet conversion

---

modules/c++/io/include/io/BufferViewStream.h

* BufferView should be just passed in by const ref and held by value (a "copy" of the BufferView is still just the pointer and size)
* Added a 'using' line to make it easier to use

BufferViewStream niceties

---

modules/c++/types/include/import/types.h
modules/c++/types/include/types/PageRowCol.h
modules/c++/types/unittests/test_page_row_col.cpp

A new class `PageRowCol` was added to the types library. The interface mirrors `RowCol` with a few exceptions:
* `volume()` method instead of `area()`
* no `std::pair` constructor
* added a new constructor taking a scalar page and a `RowCol`

Add PageRowCol type with a similar implementation to RowCol.

---

modules/c++/io/include/import/io.h
modules/c++/io/include/io/StreamSplitter.h
modules/c++/io/source/StreamSplitter.cpp
modules/c++/io/unittests/test_stream_splitter.cpp

This class is a more efficient alternative to the `InputStream::readln` method, which reads 1 byte at a time from the stream.

Add StreamSplitter for efficient line-by-line stream reading

---

modules/c++/io/include/io/StreamSplitter.h
modules/c++/io/source/StreamSplitter.cpp

Changed `&mBuffer[mBufferEnd]` to `mBuffer.data() + mBufferEnd` to avoid indexing the element past the end of a vector when only its address is needed.

Fix vector index issue

---

modules/c++/math.poly/include/math/poly/Fit.h
modules/c++/math.poly/unittests/test_llsq.cpp

When fitting vector-valued polynomial coefficients, the order for an individual component's fit may be _lower_ than the requested order. This can occur if the highest order coefficient (and any sequentially lower order coefficients) are identically 0 -- these coefficients will be pruned from the polynomial in `transformInput` during the application of a (potentially noop) shift at the end of fitting. In these cases, assembly of the vector-valued coefficients would result in an OOB exception, as one or more polynomials may not have the appropriate number of coefficients. In the fix, missing high-order coefficients are set to 0.0.
Note that in the case of _all_ polynomial orders resulting in a reduced order we still return a polynomial of the requested order, with the missing coefficients …

Fixed failure to account for order reduction in vector-valued polynomial fits

---

modules/c++/cli/include/cli/Results.h
modules/c++/dbi/include/dbi/DatabaseClientFactory.h
modules/c++/dbi/source/DatabaseClientFactory.cpp
modules/c++/io/include/io/FileUtils.h
modules/c++/io/source/FileUtils.cpp
modules/c++/net/include/net/URL.h
modules/c++/net/source/URL.cpp
modules/c++/sio.lite/include/sio/lite/FileHeader.h
modules/c++/sio.lite/include/sio/lite/UserDataDictionary.h
modules/c++/sio.lite/source/FileHeader.cpp
modules/c++/str/include/str/Convert.h
modules/c++/unique/include/unique/UUID.hpp
modules/c++/unique/source/UUID.cpp

Exception specifications were discouraged in C++11, deprecated in C++14,
and removed in C++17.
Get rid of them so that newer compilers stop warning about them.

Remove exception specifications.

---

modules/c++/sys/include/sys/AbstractOS.h
modules/c++/sys/include/sys/OSUnix.h
modules/c++/sys/include/sys/OSWin32.h
modules/c++/sys/source/OSUnix.cpp
modules/c++/sys/source/OSWin32.cpp
modules/c++/sys/tests/OSTest.cpp

Added `OS::getNumPhysicalCPUs()` to return the physical core count (as opposed to `OS::getNumCPUs()` which returns the logical core count).
__Unix implementation__: Scan for `thread_siblings_list` files under `/sys/devices/system/cpu/cpu*/topology/` and count the number of unique entries across files. 
__Windows implementation__: Throw `NotYetImplemented`. Not as simple as `getNumCPUs()`, and not needed at this time. A reference implementation for how to use `GetLogicalProcessorInformationEx` is at https://devblogs.microsoft.com/oldnewthing/?p=2823.

Physical core count

---

modules/c++/sys/include/sys/AbstractOS.h
modules/c++/sys/include/sys/OSUnix.h
modules/c++/sys/include/sys/OSWin32.h
modules/c++/sys/source/OSUnix.cpp
modules/c++/sys/source/OSWin32.cpp
modules/c++/sys/tests/CPUTest.cpp

Added affinity-based CPU count reporting to `OS`, available through `getNumCPUsAvailable` and `getNumPhysicalCPUsAvailable`. On Linux, these functions use `sched_getaffinity` and associated helpers to report total and physical CPU counts that may have been restricted by `numactl`/`taskset`. 
On Windows, these functions throw `NotImplementedException`.

Affinity-based CPU reporting

---

modules/c++/sys/source/OSUnix.cpp

Updates to CPU count functionality on UNIX if the number of CPUs available exceeds the capacity of the default size of `cpu_set_t`.

CPU counting for large machines

---

.gitignore
modules/python/io/source/generated/coda_io.py
modules/python/io/source/generated/coda_io_wrap.cxx
modules/python/io/source/io.i
modules/python/io/unittests/test_string_conversions.py

About 9 months ago, I added #define SWIG_PYTHON_STRICT_BYTE_CHAR, to io.i, because there was a need to use StringStream with a Python bytes object. Unfortunately, this broke other things with Python3 that I didn't notice until recently.
This PR reverts that change, and adds a writeBytes method to the Python layer.

Fix writing to StringStream from Python

---

modules/c++/polygon/include/polygon/Intersections.h
modules/c++/polygon/unittests/test_polygon_mask.cpp

Enhancements to `polygon::Intersections` to handle cases when the polygon partially clips an image, e.g. only the bottom-left of an image is inside the polygon.

Enhancements to polygon::Intersections for clipping polygons

---

modules/c++/mt/include/mt/ThreadGroup.h
modules/c++/mt/source/ThreadGroup.cpp
modules/c++/mt/unittests/ThreadGroupTest.cpp
modules/c++/mt/wscript

* Added a static variable to ThreadGroup to contain the default pinning option (along with getter and setter)
* Added a method to ThreadGroup to get the current pinning option (inferred from whether `mAffinityInit` is set or a null pointer)
* Add unit tests to validate the new behavior
* Changed `mt_force_cpu_pinning` to `mt_default_cpu_pinning` in the mt wscript to reflect the change in behavior, likewise change the internal define from `MT_FORCE_PINNING` to `MT_DEFAULT_PINNING`

Make ThreadGroup default CPU pinning setting configurable at runtime

---

build/swig.py
wscript

Sometimes people try to build with SWIG with some ancient 1.x version, and the error messages aren't great when it inevitably fails. 
I just set it by major version, so if you want to use, say, 3.0.7 for your project you can, but it'll catch a setup that just doesn't make sense. 
Then I added at the top level-wscript that only gets called if you're building CODA-OSS itself, a check for the current version. Presumably if you're building with SWIG, that means you plan to change the Python bindings and check it in, so you should definitely be using the right version for that.

Fail configuration if trying to use too-old SWIG

---

modules/c++/types/include/types/Range.h
modules/c++/types/unittests/test_range.cpp

Determining if two disjoint ranges can be placed next to one another with no gap between them.

Add 'touches' member function to Range

---

modules/c++/types/include/types/Range.h
modules/c++/types/unittests/test_range.cpp

Define touching as false if either of the ranges are empty.

Updates to Range::touches for empty ranges

---

build/build.py

Explicit check to make it less confusing if you try to configure with the wrong version.

Add explicit Python version check

---

build/build.py

Attempting to build with Python 3.7.2 on Linux results in mishandled exceptions inside `GlobDirectoryWalker.next()` (see trace below). 
Based on PEP479, fix is to simply `return` instead of using `raise StopIteration`. One could also catch `StopIteration` inside of `__iter__` and `return None`, but this appears cleaner. May be overlooking something.
Tested with Python 2.7.12 and 3.7.2.
```
Traceback (most recent call last):
File "/xxx/code/coda-oss/build/build.py", line 647, in next
file = self.files[self.index]
IndexError: list index out of range
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/xxx/code/coda-oss/build/build.py", line 652, in next
raise StopIteration
StopIteration
The above exception was the direct cause of the …
```

Change 'raise StopIteration' in GlobDirectoryWalker to 'return'

---

build/build.py

The body of this method modifies global environment settings that tell waf to build shared libraries without the `lib` prefix.
This fix copies the environment before modifying it, so that it only strips the prefix when we tell it to (e.g. for TREs).

Fix building shared libraries on Linux

---

modules/c++/str/include/str/Convert.h
modules/c++/str/source/Convert.cpp
modules/c++/str/unittests/test_base_convert.cpp
modules/c++/sys/source/LocalDateTime.cpp
modules/c++/sys/source/UTCDateTime.cpp

Two bugs:
- Calling `toString<uint8_t>` shouldn't try to interpret this as ASCII. This was causing garbage and segfaults downstream
- A couple issues with the dayOfWeek value in sys::DateTime. It should always be in [1,7] for us. `struct tm` has the value in [0,6], so we want to subtract 1 when converting to that. 
FYI @dstarinshak

8 bit integer to string

---

modules/c++/mem/source/ScratchMemory.cpp
modules/c++/mem/unittests/test_scratch_memory.cpp

This test was intermittently failing. Writing into erased segments was causing it to overwrite the expected data.
Is this correct? I'm not sure of the intended usage of this class, so possibly the original behavior was the desired operation and should have passed. 
The changes in ScratchBuffer.cpp were problems flagged by cppcheck while debugging.

Fix incorrect checking in unittest

---

modules/c++/sys/unittests/test_datetime.cpp

so, e.g., 59.23 should be valid.

Fix incorrect range check. Seconds are floating-point values,

---

build/build.py
modules/c++/config/wscript

support C++11.
`conf.check()` calls use the configured compile flags, one of which is
-std=c++11. We have to be sure that checking for C++11 support happens
before any other `conf.check` calls, or those checks will fail for the
wrong reason (i.e. not recognizing the -std=c++11 flag).

Fix confusing configure error message when using a compiler that doens't

---

.clang-format

This style file produces an empty/minimal diff on most files I ran it on. Most of the changes it makes/suggests are for issues that would have been a violation anyway. 
My intention is require this for "my" projects (SIX, NITRO). 
For wider CODA, I worry that this will be rather useless without widespread adoption, and I'm not sure how to make that happen.

Add a .clang-format file based on GitLab style guide

---

.github/workflows/build_unittest.yml
conanfile.py

closes #355 
This changes the default location for Conan builds on Windows, to work around path length limitations in the Visual Studio compiler and, in some cases, Windows.
Normally this is configured by the `user_home_short` setting in ~/.conan/conan.conf or the environment variable `CONAN_USER_HOME_SHORT`. If these are not selected, it defaults to `C:\.conan` which may require admin privileges to create.
There is no documented way to change this default within the recipe, but this solution seems to work well. This change configures the Conan recipe to detect whether `CONAN_USER_HOME_SHORT` is set and if not, set it to `~/.conan_short`. This is Conan's default for Cygwin builds.
This also avoids overriding `conan.conf`, since a value configured there is just copied to the environment …

Place default short_paths location within user directory

---

modules/c++/xml.lite/include/xml/lite/Attributes.h
modules/c++/xml.lite/include/xml/lite/Element.h
modules/c++/xml.lite/source/Attributes.cpp
modules/c++/xml.lite/source/Element.cpp
modules/c++/xml.lite/unittests/test_xmlattribute.cpp
modules/c++/xml.lite/unittests/test_xmlelement.cpp

A lot of client code does the exact same thing when using `xml.lite`.  This submission tries to incorporate some of the common use-cases, while still being "lite."
Also, add some more unittests for `xml.lite`, in particular to test the new featrues.

make it easier to use xml.lite

---

modules/c++/except/include/except/Throwable.h
modules/c++/include/TestCase.h

It can be quite convenient to derive from `std::exception` as often one less `catch` will be needed and we'll have standard `what()`.  But doing so could break existing code as `catch (const std::exception&)` will catch `except::Throwable` when it didn't before.
By default, this is disabled; it can be turned on by `CODA_OSS_Throwable_isa_std_exception_`.

allow except::Throwable to derive from std::exception

---

modules/c++/sys/include/import/sys.h
modules/c++/sys/include/sys/CStdDef.h
modules/c++/sys/unittests/test_byte_swap.cpp

Create a `sys::Byte` that is the same as `std::byte` in C++17.
Clients can get `std::byte` w/o C++17 by using `CODA_OSS_DEFINE_std_byte_` or `CODA_OSS_AUGMENT_std_namespace`.

add sys::Byte

---

modules/c++/except/include/except/Throwable.h
modules/c++/include/TestCase.h

Clients can determine whether `Throwable` derives from `std::exception`, so the macro shouldn't be "private."

remove trailing underscore from macro

---

modules/c++/mem/include/mem/SharedPtrCpp11.h
modules/c++/mem/unittests/test_unique_ptr.cpp
modules/c++/mem/wscript

`std::auto_ptr` has been removed in C++17 (it has been depreciated since C++11, use `std::unique_ptr`).
For return values and member data, `std::unique_ptr` is often a drop-in replacement for `std::auto_ptr`, no code changes needed.  By providing `mem::auto_ptr` as an alias for one or the other; code can build with C++17 while still supporting C++11.
Note that parameters often need to be `std::unique_ptr&&` and used with `std::move`.  But since `std::unique_ptr` is part of C++11, overloading works:
```
void foo(std::unique_ptr<T>&&); // explicit support for std::unique_ptr
void foo(mem::auto_ptr<T>); // existing code

add mem::auto_ptr for transition to C++17

---

modules/c++/sys/include/sys/AbstractOS.h
modules/c++/sys/include/sys/FileFinder.h
modules/c++/sys/include/sys/Filesystem.h
modules/c++/sys/include/sys/Path.h
modules/c++/sys/source/AbstractOS.cpp
modules/c++/sys/source/Path.cpp
modules/c++/sys/unittests/test_os.cpp
modules/c++/sys/unittests/test_path.cpp

This makes it easy to write C++ code that works like SHELL code. This can be especially convenient for various utilities or testing where an environment variable specifies a "root" directory.

produce a new Path::expandEnviromentVariables() function

---

modules/c++/numpyutils/wscript

There was a missing required library in this wscript which caused some tests to fail to build. This fixes the issue.

Fix wscript to successfully build test_num_elements

---

modules/c++/math.linear/source/Line2D.cpp

Migrating a subtree patch to oss that applies the same principle to horizontal calculations as is applied to vertical ones

Fix for numerical precision issues surrounding horizontal lines

---

modules/c++/config/include/config/compiler_extensions.h

` CODA_OSS_mark_symbol_unused(_import_array);`
```c++
// Compile with:
// cl.exe /EHsc foo.cpp
#include <iostream>
void
foo() {
std::cout << "error if this shows up!" << std::endl;
}
int
main() {
std::cout << "before" <<std::endl;
foo;
std::cout << "after" <<std::endl;
return 0;
}
```

Macros to narrowly target disabling warnings

---

modules/drivers/zlib/CMakeLists.txt
modules/drivers/zlib/wscript

This header clashes with glibc's crypt.h header.
The minizip crypt.h header is deleted after unpacking the zlib tarfile, and preprocessor options are configured to disable its inclusion.

Disable encryption support in minizip build and remove crypt.h header

---

modules/c++/logging/include/logging/Filter.h
modules/c++/logging/include/logging/Filterer.h
modules/c++/logging/include/logging/Handler.h
modules/c++/logging/include/logging/Logger.h
modules/c++/logging/include/logging/StreamHandler.h
modules/c++/logging/source/Filterer.cpp
modules/c++/logging/source/Handler.cpp
modules/c++/logging/source/Logger.cpp
modules/c++/logging/source/StreamHandler.cpp
modules/c++/logging/unittests/test_exception_logger.cpp
modules/c++/logging/unittests/test_rotating_log.cpp

There was a missing `virtual` on a `filter()` method; adding it has the potential to break existing code, but that code is broken anyway (and the use-case for an actual break is obscure).  Trying to repair the damage without even the remote possibility of breaking existing code creates a huge mess.  🤞🏻
While I was in the code, used the opportunity to improve support for `std::unique_ptr`.

added missing "virtual", support unique_ptr

---

.github/workflows/build_unittest.yml

`windows-latest` is now 2022 which breaks our ancient `waf` build; explicitly specify `windows-2019` which is still supported.

use windows-2019 environment

---

ReleaseNotes.md
build/build.py
modules/c++/math.poly/include/math/poly/TwoD.hpp
modules/c++/math.poly/unittests/test_2d_poly.cpp

From E. Williams:
> We came across a bug inside the `Poly2D::atY()` function.  Attached is the fix (with unit tests).
>
> While updating the unit tests, I took the opportunity to improve the `flipXY()` behavior which is also tested by the same new unit tests.

Poly2D::atY() bugfix

---

UnitTest/TestCase.h
modules/c++/include/TestCase.h
modules/c++/str/include/str/Convert.h
modules/c++/str/include/str/EncodedString.h
modules/c++/str/include/str/EncodedStringView.h
modules/c++/str/include/str/Manip.h
modules/c++/str/source/Convert.cpp
modules/c++/str/source/Encoding.cpp
modules/c++/str/unittests/test_base_convert.cpp

Overloading is usually better than specialization; this PR tweaks `toString()` to make overloading work better.  It also uses some "template magic" to hopefully minimize the need for specialization (and ... 🤞🏻 ... not break too much existing code).

tweak toString() to reduce specialization

---

modules/c++/sys/include/sys/FileFinder.h
modules/c++/sys/source/FileFinder.cpp

Add some utility routines to find files from a build/install directory.  Complications include: both CMake and waf builds, and a project could be **externals** in another project.

utilities to find files from a build

---

modules/drivers/xml/xerces/CMakeLists.txt

Need to install the cmake-modified (autoconf) header after installing the xercesc source tree. The source tree contains a default header at the same path that will clobber the cmake-modified copy otherwise.

Fix install order for cmake-modified xerces header

---

UnitTest/TestCase.h
UnitTest/pch.h
modules/c++/coda-oss-lite.vcxproj
modules/c++/coda-oss-lite.vcxproj.filters
modules/c++/mem/include/mem/AutoPtr.h
modules/c++/mem/unittests/test_unique_ptr.cpp
modules/c++/pch.h

Need a "smart pointer" class that is copyable for SWIG bindings :-(

mem::AutoPtr class to aid C++17 transition

---

UnitTest/TestCase.h
UnitTest/pch.h
modules/c++/coda-oss-lite.vcxproj
modules/c++/coda-oss-lite.vcxproj.filters
modules/c++/mem/include/mem/AutoPtr.h
modules/c++/mem/unittests/test_unique_ptr.cpp
modules/c++/pch.h

Changing classes that use `std::unique_ptr` to not be copyable can require some cascading changes; something that may not be desirable at a particular moment.  This effectively brings back `std::auto_ptr` as `mem::AutoPtr` and using `std::unique_ptr` internally.

mem::AutoPtr for C++17

---

build/build.py
modules/c++/coda_oss/include/coda_oss/CPlusPlus.h
modules/c++/coda_oss/include/coda_oss/memory.h
modules/c++/coda_oss/include/coda_oss/type_traits.h
modules/c++/io/include/io/PipeStream.h
modules/c++/logging/include/logging/FileHandler.h
modules/c++/math.linear/include/math/linear/Matrix2D.h
modules/c++/mem/CMakeLists.txt
modules/c++/mem/include/mem/ScopedPtr.h
modules/c++/mt/CMakeLists.txt
modules/c++/mt/include/mt/BasicThreadPool.h
modules/c++/mt/include/mt/Singleton.h
modules/c++/mt/wscript
modules/c++/std/include/std/bit
modules/c++/std/include/std/cstddef
modules/c++/std/include/std/filesystem
modules/c++/std/include/std/memory
modules/c++/std/include/std/optional
modules/c++/std/include/std/span
modules/c++/std/include/std/string
modules/c++/std/include/std/type_traits
modules/c++/xml.lite/include/xml/lite/Document.h
modules/c++/xml.lite/include/xml/lite/MinidomHandler.h
modules/c++/xml.lite/source/ValidatorXerces.cpp

We're still using an old version of the Intel compiler that only partially implements C++14.

restore C++14 workarounds for older compilers

---

build/build.py

Fix bug where `-g` debug flags were not being handled correctly for `waf` builds.  On master calling:
* `python waf configure --prefix=install --enable-debugging`
* `python waf install`  
Adds debug flags for `gcc` calls **but not** `g++`.  See below:
Obtained these dumps from running `python waf install --verbose`
```
'/usr/bin/gcc', '-fPIC', '-Wall', '-Wno-deprecated-declarations', '-ggdb3', '-Og', '-m64',
```
**note missing -g flags**
```
'/usr/bin/g++', '-fPIC', '-std=c++11', '-Wall', '-Wno-deprecated-declarations', '-m64',
```
* Run: `python waf configure --prefix=install --enable-debugging`
* Run: `python waf install`
* Verify ability to debug executables with `gdb`
- Set a breakpoint in an executable and print some stuff
- Here's an example I used to verify this: `gdb …

move debug -g flags to be turned on only if debugging

---

modules/c++/xml.lite/include/xml/lite/Document.h
modules/c++/xml.lite/unittests/test_soapelements.cpp

Program dependent on coda-oss has class that inherits and overrides createElement function from document in the xml lite class. This pull request changes createElement back to virtual.

Change xml lite function to virtual

---

ReleaseNotes.md
modules/c++/config/include/config/Version.h

* Final 🤞🏻 **C++11 release  from [master](https://github.com/mdaus/coda-oss/tree/master)
not [main](https://github.com/mdaus/coda-oss/tree/main)/C++14** as releases since
[2022-08-30](https://github.com/mdaus/coda-oss/releases/tag/2022-08-30) have been.
* [HDF5](https://www.hdfgroup.org/) [source code](https://github.com/HDFGroup/hdf5) added (not built).
* *waf* self-extractor rebuilt to fix FIPS error.
* Better debug/release configurations for *waf* builds.
* Minor tweaks from other projects.

C++11/master release

---

modules/c++/mt/include/mt/Algorithm.h
modules/c++/mt/unittests/Runnable1DTest.cpp

There was a `transform_async()` utility here, but I removed it.
First of all, C++11's `std::async()` is now (in 2023) thought of as maybe a bit "half baked," and perhaps shouldn't be emulated.  Then, C++17 added parallel algorithms which might be a better ... although we're still at C++14.

remove transform_async()

---

modules/c++/sys/source/Path.cpp
modules/c++/sys/unittests/test_path.cpp

Be sure our `Path::isAbolute()` matches `std::filesystem::path::absolute()` since we use that in pre-C++17.

be sure our Path::isAbolute() matches std::filesystem::path::absolute()

---

build/dumplibimpl.py

py2 => py3 changed the location of `.pyc` files.
`.pyc` files could not be found, resulting in wrong behavior
Updated search location to find files in `__pycache__`

fix `python3 waf dumplib`

---

UnitTest/UnitTest.vcxproj
build/build.py
modules/c++/coda-oss-lite.vcxproj
modules/c++/sys/include/sys/AbstractOS.h
modules/c++/sys/include/sys/OSUnix.h
modules/c++/sys/include/sys/OSWin32.h
modules/c++/sys/source/OSUnix.cpp
modules/c++/sys/source/OSWin32.cpp
modules/c++/sys/unittests/test_os.cpp

Add a new `sys::OS::getSIMDInstructionSet()` to return the **runtime** SIMD instruction set that's available.  One of three values is supported:
* [SSE2](https://en.wikipedia.org/wiki/SSE2) (required)
* [AVX2](https://en.wikipedia.org/wiki/Advanced_Vector_Extensions)
* [AVX512](https://en.wikipedia.org/wiki/AVX-512)
Also enable [haswell](https://en.wikipedia.org/wiki/Haswell_%28microarchitecture%29) (from 2013) at higher optimization levels (*waf* builds only).

OS::getSIMDInstructionSet() utility

---

modules/c++/coda_oss/include/coda_oss/optional_.h

Our `coda_oss::optional` failed to compile in certain cases.

our optional<> is now closer to C++17

---

modules/c++/cli/include/cli/Value.h
modules/c++/cli/source/ArgumentParser.cpp
modules/c++/pch.h
modules/c++/plugin/include/plugin/BasicPluginManager.h
modules/c++/str/include/str/Format.h
modules/c++/str/source/Format.cpp
modules/c++/sys/source/OSUnix.cpp
modules/c++/sys/source/OSWin32.cpp
modules/c++/xml.lite/source/Attributes.cpp

Use overloads rather than varargs for `std::format()`.

use overloads rather than varargs for std::format()

---

.github/workflows/build_unittest.yml
CMakeLists.txt
cmake/CodaBuild.cmake

Add `ENABLE_AVX2` and `ENABLE_AVX512F` Cmake options.

enable AVX2 and AVX512F CMake builds

---

modules/c++/except/include/except/Error.h
modules/c++/except/include/except/Exception.h
modules/c++/except/include/except/Throwable.h
modules/c++/except/source/Throwable.cpp

`Throwable` always inherits from `std::exception`, `ThrowableEx` (and friends) have been removed.

Throwable always inherits from std::exception

---

.gitattributes

add extensions for `.log` and known Windows/Linux binaries

add extensions for .log and known Windows/Linux binaries

---

modules/c++/xml.lite/include/xml/lite/UtilitiesXerces.h
modules/c++/xml.lite/include/xml/lite/ValidatorXerces.h
modules/c++/xml.lite/include/xml/lite/XMLReaderXerces.h
modules/c++/xml.lite/source/UtilitiesXerces.cpp
modules/c++/xml.lite/source/ValidatorXerces.cpp
modules/c++/xml.lite/unittests/test_xmlparser.cpp

Change the implementation of *XercesContext* to use a `std::shared_ptr`; this way Xerces is really only initialized/destroyed once.

Only need to actually create/destroy Xerces once

---

.github/workflows/build_unittest.yml

https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12

update to latest versions of various actions

---

UnitTest/UnitTest.vcxproj
UnitTest/UnitTest.vcxproj.filters
UnitTest/sys.cpp
modules/c++/coda-oss.vcxproj
modules/c++/coda-oss.vcxproj.filters
modules/c++/sys/include/sys/Ximd.h
modules/c++/sys/unittests/test_ximd.cpp

[std::experimental::simd}(https://en.cppreference.com/w/cpp/experimental/simd) is currently targeted for C++26 🤞🏻.
In the meantime, it's fairly easy to hook up a simple version by using `std::array<T, 4>`; and thanks to auto-vectorization, performance isn't abysmal.

provide a simple implementation of std::experimental::simd

---

UnitTest/mt.cpp
modules/c++/mt/include/mt/Algorithm.h
modules/c++/mt/unittests/test_mt_byte_swap.cpp

Provide `mt::Transfor_par()` as a work-around for not having `std::transform(par, ...)` until C++17,

add back transform_async() as Transform_par()

---

modules/c++/include/TestCase.h
modules/c++/sys/source/OSWin32.cpp

- Fix AVX compilation errors on older MS compilers
- Fix `C4127: Conditional Expression is Constant` error on newer MS Compilers

Windows Build enhancements

---

modules/c++/sys/source/OSWin32.cpp

target avx feature macros more precisely

Windows Avx macro tweak

---

modules/c++/mem/include/mem/SwapBuffer.h

Allow derived classes that offer additional functionality (such as locking)

Allowed derived classes of SwapBuffer

---

build/build.py
modules/c++/net/wscript
modules/drivers/xml/xerces/wscript

When building changes I had made in coda I was getting an error something like `unable to create directory /test_utils`. With the help of Eric Williams and Charles Vink I tracked the problem down to the fact that build.py was relying on the PYTHONDIR variable being defined if `--pydir` was not specified during the configure stage. This fork removes that assumption and changes the default to `join(Options.options.prefix, 'lib/python/site-packages')`. This allows things to build without error without specifying `--pydir`.
I also found when building code under RHEL 8 I encountered an issue that the NSL libraries couldn't be found but are there. I found that removing the search works in both RHEL 7 and 8 so I'm proposing that change also.
I'm not sure how to test this change purely in …

Changes the default value for 'install_pydir'

---

modules/c++/math.poly/include/math/poly/Fixed1D.h
modules/c++/math.poly/include/math/poly/Fixed2D.h

Make the coefficients of the `Fixed1D` and `Fixed2D` polynomials `std::array<T, Order>` instead of `T[Order]` so that the coefficients can be returned. Added a few constructors to the `Fixed1D` type.

Make fixed polys more user friendly

---

.github/workflows/build_unittest.yml
modules/c++/math.poly/include/math/poly/Fixed1D.h
modules/c++/math.poly/include/math/poly/Fixed2D.h
modules/c++/math.poly/include/math/poly/OneD.hpp
modules/c++/math.poly/unittests/test_1d_poly.cpp
modules/c++/math.poly/unittests/test_fixed_1d_poly.cpp

My initial goal here was to add `velocity` and `acceleration` functions to the `Fixed1D` polynomial which were similar to the `OneD` versions. After looking closer at the [current implementation](https://github.com/mdaus/coda-oss/blob/036b17d68e937ebf45189cbb7728e82e2877eef3/modules/c%2B%2B/math.poly/include/math/poly/OneD.hpp#L156-L161) I thought it would probably be more performant to directly evaluate the velocity and acceleration from the existing coefficients instead of creating a new polynomial (or two in the case of the acceleration) and then evaluating that. 
I refactored the two functions in `OneD` poly and added them to the `Fixed1D`, then made a simple micro-benchmark test which checked the new  values matched the old then called each version a bunch of times and reported the …

Add explicit implementations of polynomial velocity and acceleration
